import { Inter } from "next/font/google";

// css
import "./globals.css";

//importing components
import Header from "./components/Header";

// context
import FinanceContextProvider from "./components/context/FinanceContext";
import AuthContextProvider from "./components/context/AuthContext";
import "react-toastify/dist/ReactToastify.css";

//toast
import { toast, ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <FinanceContextProvider>
            <ToastContainer />
            <Header />
            {children}
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
